// Code generated by codegen; DO NOT EDIT.

package ssoadmin

import (
	"github.com/cloudquery/plugin-sdk/schema"

	"github.com/OpsHelmInc/cloudquery/client"
)

func Instances() *schema.Table {
	return &schema.Table{
		Name:        "aws_ssoadmin_instances",
		Description: `https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_InstanceMetadata.html`,
		Resolver:    fetchSsoadminInstances,
		Multiplex:   client.ServiceAccountRegionMultiplexer("identitystore"),
		Columns: []schema.Column{
			{
				Name:     "created_date",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("CreatedDate"),
			},
			{
				Name:     "identity_store_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("IdentityStoreId"),
			},
			{
				Name:     "instance_arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("InstanceArn"),
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "owner_account_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("OwnerAccountId"),
			},
			{
				Name:     "status",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Status"),
			},
			{
				Name:     "status_reason",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("StatusReason"),
			},
		},

		Relations: []*schema.Table{
			PermissionSets(),
		},
	}
}
