// Code generated by codegen; DO NOT EDIT.

package kafka

import (
	"context"

	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/OpsHelmInc/cloudquery/plugin-sdk/schema"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/kafka"
)

func fetchKafkaConfigurations(ctx context.Context, meta schema.ClientMeta, parent *schema.Resource, res chan<- interface{}) error {
	var input kafka.ListConfigurationsInput
	c := meta.(*client.Client)
	svc := c.Services().Kafka
	for {
		response, err := svc.ListConfigurations(ctx, &input)
		if err != nil {
			return err
		}
		res <- response.Configurations
		if aws.ToString(response.NextToken) == "" {
			break
		}
		input.NextToken = response.NextToken
	}
	return nil
}
