// Code generated by MockGen. DO NOT EDIT.
// Source: cloudfront.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cloudfront "github.com/aws/aws-sdk-go-v2/service/cloudfront"
	gomock "github.com/golang/mock/gomock"
)

// MockCloudfrontClient is a mock of CloudfrontClient interface.
type MockCloudfrontClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudfrontClientMockRecorder
}

// MockCloudfrontClientMockRecorder is the mock recorder for MockCloudfrontClient.
type MockCloudfrontClientMockRecorder struct {
	mock *MockCloudfrontClient
}

// NewMockCloudfrontClient creates a new mock instance.
func NewMockCloudfrontClient(ctrl *gomock.Controller) *MockCloudfrontClient {
	mock := &MockCloudfrontClient{ctrl: ctrl}
	mock.recorder = &MockCloudfrontClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudfrontClient) EXPECT() *MockCloudfrontClientMockRecorder {
	return m.recorder
}

// DescribeFunction mocks base method.
func (m *MockCloudfrontClient) DescribeFunction(arg0 context.Context, arg1 *cloudfront.DescribeFunctionInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.DescribeFunctionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeFunction", varargs...)
	ret0, _ := ret[0].(*cloudfront.DescribeFunctionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeFunction indicates an expected call of DescribeFunction.
func (mr *MockCloudfrontClientMockRecorder) DescribeFunction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeFunction", reflect.TypeOf((*MockCloudfrontClient)(nil).DescribeFunction), varargs...)
}

// DescribeKeyValueStore mocks base method.
func (m *MockCloudfrontClient) DescribeKeyValueStore(arg0 context.Context, arg1 *cloudfront.DescribeKeyValueStoreInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.DescribeKeyValueStoreOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeKeyValueStore", varargs...)
	ret0, _ := ret[0].(*cloudfront.DescribeKeyValueStoreOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeKeyValueStore indicates an expected call of DescribeKeyValueStore.
func (mr *MockCloudfrontClientMockRecorder) DescribeKeyValueStore(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeKeyValueStore", reflect.TypeOf((*MockCloudfrontClient)(nil).DescribeKeyValueStore), varargs...)
}

// GetAnycastIpList mocks base method.
func (m *MockCloudfrontClient) GetAnycastIpList(arg0 context.Context, arg1 *cloudfront.GetAnycastIpListInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetAnycastIpListOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAnycastIpList", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetAnycastIpListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnycastIpList indicates an expected call of GetAnycastIpList.
func (mr *MockCloudfrontClientMockRecorder) GetAnycastIpList(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnycastIpList", reflect.TypeOf((*MockCloudfrontClient)(nil).GetAnycastIpList), varargs...)
}

// GetCachePolicy mocks base method.
func (m *MockCloudfrontClient) GetCachePolicy(arg0 context.Context, arg1 *cloudfront.GetCachePolicyInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetCachePolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCachePolicy", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetCachePolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachePolicy indicates an expected call of GetCachePolicy.
func (mr *MockCloudfrontClientMockRecorder) GetCachePolicy(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachePolicy", reflect.TypeOf((*MockCloudfrontClient)(nil).GetCachePolicy), varargs...)
}

// GetCachePolicyConfig mocks base method.
func (m *MockCloudfrontClient) GetCachePolicyConfig(arg0 context.Context, arg1 *cloudfront.GetCachePolicyConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetCachePolicyConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCachePolicyConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetCachePolicyConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachePolicyConfig indicates an expected call of GetCachePolicyConfig.
func (mr *MockCloudfrontClientMockRecorder) GetCachePolicyConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachePolicyConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetCachePolicyConfig), varargs...)
}

// GetCloudFrontOriginAccessIdentity mocks base method.
func (m *MockCloudfrontClient) GetCloudFrontOriginAccessIdentity(arg0 context.Context, arg1 *cloudfront.GetCloudFrontOriginAccessIdentityInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetCloudFrontOriginAccessIdentityOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCloudFrontOriginAccessIdentity", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetCloudFrontOriginAccessIdentityOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudFrontOriginAccessIdentity indicates an expected call of GetCloudFrontOriginAccessIdentity.
func (mr *MockCloudfrontClientMockRecorder) GetCloudFrontOriginAccessIdentity(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudFrontOriginAccessIdentity", reflect.TypeOf((*MockCloudfrontClient)(nil).GetCloudFrontOriginAccessIdentity), varargs...)
}

// GetCloudFrontOriginAccessIdentityConfig mocks base method.
func (m *MockCloudfrontClient) GetCloudFrontOriginAccessIdentityConfig(arg0 context.Context, arg1 *cloudfront.GetCloudFrontOriginAccessIdentityConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetCloudFrontOriginAccessIdentityConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCloudFrontOriginAccessIdentityConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetCloudFrontOriginAccessIdentityConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudFrontOriginAccessIdentityConfig indicates an expected call of GetCloudFrontOriginAccessIdentityConfig.
func (mr *MockCloudfrontClientMockRecorder) GetCloudFrontOriginAccessIdentityConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudFrontOriginAccessIdentityConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetCloudFrontOriginAccessIdentityConfig), varargs...)
}

// GetConnectionGroup mocks base method.
func (m *MockCloudfrontClient) GetConnectionGroup(arg0 context.Context, arg1 *cloudfront.GetConnectionGroupInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetConnectionGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConnectionGroup", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetConnectionGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectionGroup indicates an expected call of GetConnectionGroup.
func (mr *MockCloudfrontClientMockRecorder) GetConnectionGroup(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionGroup", reflect.TypeOf((*MockCloudfrontClient)(nil).GetConnectionGroup), varargs...)
}

// GetConnectionGroupByRoutingEndpoint mocks base method.
func (m *MockCloudfrontClient) GetConnectionGroupByRoutingEndpoint(arg0 context.Context, arg1 *cloudfront.GetConnectionGroupByRoutingEndpointInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetConnectionGroupByRoutingEndpointOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConnectionGroupByRoutingEndpoint", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetConnectionGroupByRoutingEndpointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectionGroupByRoutingEndpoint indicates an expected call of GetConnectionGroupByRoutingEndpoint.
func (mr *MockCloudfrontClientMockRecorder) GetConnectionGroupByRoutingEndpoint(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionGroupByRoutingEndpoint", reflect.TypeOf((*MockCloudfrontClient)(nil).GetConnectionGroupByRoutingEndpoint), varargs...)
}

// GetContinuousDeploymentPolicy mocks base method.
func (m *MockCloudfrontClient) GetContinuousDeploymentPolicy(arg0 context.Context, arg1 *cloudfront.GetContinuousDeploymentPolicyInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetContinuousDeploymentPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContinuousDeploymentPolicy", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetContinuousDeploymentPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContinuousDeploymentPolicy indicates an expected call of GetContinuousDeploymentPolicy.
func (mr *MockCloudfrontClientMockRecorder) GetContinuousDeploymentPolicy(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContinuousDeploymentPolicy", reflect.TypeOf((*MockCloudfrontClient)(nil).GetContinuousDeploymentPolicy), varargs...)
}

// GetContinuousDeploymentPolicyConfig mocks base method.
func (m *MockCloudfrontClient) GetContinuousDeploymentPolicyConfig(arg0 context.Context, arg1 *cloudfront.GetContinuousDeploymentPolicyConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetContinuousDeploymentPolicyConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContinuousDeploymentPolicyConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetContinuousDeploymentPolicyConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContinuousDeploymentPolicyConfig indicates an expected call of GetContinuousDeploymentPolicyConfig.
func (mr *MockCloudfrontClientMockRecorder) GetContinuousDeploymentPolicyConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContinuousDeploymentPolicyConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetContinuousDeploymentPolicyConfig), varargs...)
}

// GetDistribution mocks base method.
func (m *MockCloudfrontClient) GetDistribution(arg0 context.Context, arg1 *cloudfront.GetDistributionInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetDistributionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDistribution", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetDistributionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistribution indicates an expected call of GetDistribution.
func (mr *MockCloudfrontClientMockRecorder) GetDistribution(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistribution", reflect.TypeOf((*MockCloudfrontClient)(nil).GetDistribution), varargs...)
}

// GetDistributionConfig mocks base method.
func (m *MockCloudfrontClient) GetDistributionConfig(arg0 context.Context, arg1 *cloudfront.GetDistributionConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetDistributionConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDistributionConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetDistributionConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistributionConfig indicates an expected call of GetDistributionConfig.
func (mr *MockCloudfrontClientMockRecorder) GetDistributionConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistributionConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetDistributionConfig), varargs...)
}

// GetDistributionTenant mocks base method.
func (m *MockCloudfrontClient) GetDistributionTenant(arg0 context.Context, arg1 *cloudfront.GetDistributionTenantInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetDistributionTenantOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDistributionTenant", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetDistributionTenantOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistributionTenant indicates an expected call of GetDistributionTenant.
func (mr *MockCloudfrontClientMockRecorder) GetDistributionTenant(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistributionTenant", reflect.TypeOf((*MockCloudfrontClient)(nil).GetDistributionTenant), varargs...)
}

// GetDistributionTenantByDomain mocks base method.
func (m *MockCloudfrontClient) GetDistributionTenantByDomain(arg0 context.Context, arg1 *cloudfront.GetDistributionTenantByDomainInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetDistributionTenantByDomainOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDistributionTenantByDomain", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetDistributionTenantByDomainOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistributionTenantByDomain indicates an expected call of GetDistributionTenantByDomain.
func (mr *MockCloudfrontClientMockRecorder) GetDistributionTenantByDomain(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistributionTenantByDomain", reflect.TypeOf((*MockCloudfrontClient)(nil).GetDistributionTenantByDomain), varargs...)
}

// GetFieldLevelEncryption mocks base method.
func (m *MockCloudfrontClient) GetFieldLevelEncryption(arg0 context.Context, arg1 *cloudfront.GetFieldLevelEncryptionInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetFieldLevelEncryptionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFieldLevelEncryption", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetFieldLevelEncryptionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFieldLevelEncryption indicates an expected call of GetFieldLevelEncryption.
func (mr *MockCloudfrontClientMockRecorder) GetFieldLevelEncryption(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldLevelEncryption", reflect.TypeOf((*MockCloudfrontClient)(nil).GetFieldLevelEncryption), varargs...)
}

// GetFieldLevelEncryptionConfig mocks base method.
func (m *MockCloudfrontClient) GetFieldLevelEncryptionConfig(arg0 context.Context, arg1 *cloudfront.GetFieldLevelEncryptionConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetFieldLevelEncryptionConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFieldLevelEncryptionConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetFieldLevelEncryptionConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFieldLevelEncryptionConfig indicates an expected call of GetFieldLevelEncryptionConfig.
func (mr *MockCloudfrontClientMockRecorder) GetFieldLevelEncryptionConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldLevelEncryptionConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetFieldLevelEncryptionConfig), varargs...)
}

// GetFieldLevelEncryptionProfile mocks base method.
func (m *MockCloudfrontClient) GetFieldLevelEncryptionProfile(arg0 context.Context, arg1 *cloudfront.GetFieldLevelEncryptionProfileInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetFieldLevelEncryptionProfileOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFieldLevelEncryptionProfile", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetFieldLevelEncryptionProfileOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFieldLevelEncryptionProfile indicates an expected call of GetFieldLevelEncryptionProfile.
func (mr *MockCloudfrontClientMockRecorder) GetFieldLevelEncryptionProfile(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldLevelEncryptionProfile", reflect.TypeOf((*MockCloudfrontClient)(nil).GetFieldLevelEncryptionProfile), varargs...)
}

// GetFieldLevelEncryptionProfileConfig mocks base method.
func (m *MockCloudfrontClient) GetFieldLevelEncryptionProfileConfig(arg0 context.Context, arg1 *cloudfront.GetFieldLevelEncryptionProfileConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetFieldLevelEncryptionProfileConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFieldLevelEncryptionProfileConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetFieldLevelEncryptionProfileConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFieldLevelEncryptionProfileConfig indicates an expected call of GetFieldLevelEncryptionProfileConfig.
func (mr *MockCloudfrontClientMockRecorder) GetFieldLevelEncryptionProfileConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldLevelEncryptionProfileConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetFieldLevelEncryptionProfileConfig), varargs...)
}

// GetFunction mocks base method.
func (m *MockCloudfrontClient) GetFunction(arg0 context.Context, arg1 *cloudfront.GetFunctionInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetFunctionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFunction", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetFunctionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFunction indicates an expected call of GetFunction.
func (mr *MockCloudfrontClientMockRecorder) GetFunction(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFunction", reflect.TypeOf((*MockCloudfrontClient)(nil).GetFunction), varargs...)
}

// GetInvalidation mocks base method.
func (m *MockCloudfrontClient) GetInvalidation(arg0 context.Context, arg1 *cloudfront.GetInvalidationInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetInvalidationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInvalidation", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetInvalidationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvalidation indicates an expected call of GetInvalidation.
func (mr *MockCloudfrontClientMockRecorder) GetInvalidation(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvalidation", reflect.TypeOf((*MockCloudfrontClient)(nil).GetInvalidation), varargs...)
}

// GetInvalidationForDistributionTenant mocks base method.
func (m *MockCloudfrontClient) GetInvalidationForDistributionTenant(arg0 context.Context, arg1 *cloudfront.GetInvalidationForDistributionTenantInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetInvalidationForDistributionTenantOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInvalidationForDistributionTenant", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetInvalidationForDistributionTenantOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvalidationForDistributionTenant indicates an expected call of GetInvalidationForDistributionTenant.
func (mr *MockCloudfrontClientMockRecorder) GetInvalidationForDistributionTenant(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvalidationForDistributionTenant", reflect.TypeOf((*MockCloudfrontClient)(nil).GetInvalidationForDistributionTenant), varargs...)
}

// GetKeyGroup mocks base method.
func (m *MockCloudfrontClient) GetKeyGroup(arg0 context.Context, arg1 *cloudfront.GetKeyGroupInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetKeyGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKeyGroup", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetKeyGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyGroup indicates an expected call of GetKeyGroup.
func (mr *MockCloudfrontClientMockRecorder) GetKeyGroup(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyGroup", reflect.TypeOf((*MockCloudfrontClient)(nil).GetKeyGroup), varargs...)
}

// GetKeyGroupConfig mocks base method.
func (m *MockCloudfrontClient) GetKeyGroupConfig(arg0 context.Context, arg1 *cloudfront.GetKeyGroupConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetKeyGroupConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKeyGroupConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetKeyGroupConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyGroupConfig indicates an expected call of GetKeyGroupConfig.
func (mr *MockCloudfrontClientMockRecorder) GetKeyGroupConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyGroupConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetKeyGroupConfig), varargs...)
}

// GetManagedCertificateDetails mocks base method.
func (m *MockCloudfrontClient) GetManagedCertificateDetails(arg0 context.Context, arg1 *cloudfront.GetManagedCertificateDetailsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetManagedCertificateDetailsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetManagedCertificateDetails", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetManagedCertificateDetailsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManagedCertificateDetails indicates an expected call of GetManagedCertificateDetails.
func (mr *MockCloudfrontClientMockRecorder) GetManagedCertificateDetails(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagedCertificateDetails", reflect.TypeOf((*MockCloudfrontClient)(nil).GetManagedCertificateDetails), varargs...)
}

// GetMonitoringSubscription mocks base method.
func (m *MockCloudfrontClient) GetMonitoringSubscription(arg0 context.Context, arg1 *cloudfront.GetMonitoringSubscriptionInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetMonitoringSubscriptionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMonitoringSubscription", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetMonitoringSubscriptionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonitoringSubscription indicates an expected call of GetMonitoringSubscription.
func (mr *MockCloudfrontClientMockRecorder) GetMonitoringSubscription(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonitoringSubscription", reflect.TypeOf((*MockCloudfrontClient)(nil).GetMonitoringSubscription), varargs...)
}

// GetOriginAccessControl mocks base method.
func (m *MockCloudfrontClient) GetOriginAccessControl(arg0 context.Context, arg1 *cloudfront.GetOriginAccessControlInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetOriginAccessControlOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOriginAccessControl", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetOriginAccessControlOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginAccessControl indicates an expected call of GetOriginAccessControl.
func (mr *MockCloudfrontClientMockRecorder) GetOriginAccessControl(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginAccessControl", reflect.TypeOf((*MockCloudfrontClient)(nil).GetOriginAccessControl), varargs...)
}

// GetOriginAccessControlConfig mocks base method.
func (m *MockCloudfrontClient) GetOriginAccessControlConfig(arg0 context.Context, arg1 *cloudfront.GetOriginAccessControlConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetOriginAccessControlConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOriginAccessControlConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetOriginAccessControlConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginAccessControlConfig indicates an expected call of GetOriginAccessControlConfig.
func (mr *MockCloudfrontClientMockRecorder) GetOriginAccessControlConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginAccessControlConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetOriginAccessControlConfig), varargs...)
}

// GetOriginRequestPolicy mocks base method.
func (m *MockCloudfrontClient) GetOriginRequestPolicy(arg0 context.Context, arg1 *cloudfront.GetOriginRequestPolicyInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetOriginRequestPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOriginRequestPolicy", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetOriginRequestPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginRequestPolicy indicates an expected call of GetOriginRequestPolicy.
func (mr *MockCloudfrontClientMockRecorder) GetOriginRequestPolicy(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginRequestPolicy", reflect.TypeOf((*MockCloudfrontClient)(nil).GetOriginRequestPolicy), varargs...)
}

// GetOriginRequestPolicyConfig mocks base method.
func (m *MockCloudfrontClient) GetOriginRequestPolicyConfig(arg0 context.Context, arg1 *cloudfront.GetOriginRequestPolicyConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetOriginRequestPolicyConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOriginRequestPolicyConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetOriginRequestPolicyConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginRequestPolicyConfig indicates an expected call of GetOriginRequestPolicyConfig.
func (mr *MockCloudfrontClientMockRecorder) GetOriginRequestPolicyConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginRequestPolicyConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetOriginRequestPolicyConfig), varargs...)
}

// GetPublicKey mocks base method.
func (m *MockCloudfrontClient) GetPublicKey(arg0 context.Context, arg1 *cloudfront.GetPublicKeyInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetPublicKeyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPublicKey", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetPublicKeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockCloudfrontClientMockRecorder) GetPublicKey(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockCloudfrontClient)(nil).GetPublicKey), varargs...)
}

// GetPublicKeyConfig mocks base method.
func (m *MockCloudfrontClient) GetPublicKeyConfig(arg0 context.Context, arg1 *cloudfront.GetPublicKeyConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetPublicKeyConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPublicKeyConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetPublicKeyConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKeyConfig indicates an expected call of GetPublicKeyConfig.
func (mr *MockCloudfrontClientMockRecorder) GetPublicKeyConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKeyConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetPublicKeyConfig), varargs...)
}

// GetRealtimeLogConfig mocks base method.
func (m *MockCloudfrontClient) GetRealtimeLogConfig(arg0 context.Context, arg1 *cloudfront.GetRealtimeLogConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetRealtimeLogConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRealtimeLogConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetRealtimeLogConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRealtimeLogConfig indicates an expected call of GetRealtimeLogConfig.
func (mr *MockCloudfrontClientMockRecorder) GetRealtimeLogConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRealtimeLogConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetRealtimeLogConfig), varargs...)
}

// GetResponseHeadersPolicy mocks base method.
func (m *MockCloudfrontClient) GetResponseHeadersPolicy(arg0 context.Context, arg1 *cloudfront.GetResponseHeadersPolicyInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetResponseHeadersPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResponseHeadersPolicy", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetResponseHeadersPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponseHeadersPolicy indicates an expected call of GetResponseHeadersPolicy.
func (mr *MockCloudfrontClientMockRecorder) GetResponseHeadersPolicy(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseHeadersPolicy", reflect.TypeOf((*MockCloudfrontClient)(nil).GetResponseHeadersPolicy), varargs...)
}

// GetResponseHeadersPolicyConfig mocks base method.
func (m *MockCloudfrontClient) GetResponseHeadersPolicyConfig(arg0 context.Context, arg1 *cloudfront.GetResponseHeadersPolicyConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetResponseHeadersPolicyConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResponseHeadersPolicyConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetResponseHeadersPolicyConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponseHeadersPolicyConfig indicates an expected call of GetResponseHeadersPolicyConfig.
func (mr *MockCloudfrontClientMockRecorder) GetResponseHeadersPolicyConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseHeadersPolicyConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetResponseHeadersPolicyConfig), varargs...)
}

// GetStreamingDistribution mocks base method.
func (m *MockCloudfrontClient) GetStreamingDistribution(arg0 context.Context, arg1 *cloudfront.GetStreamingDistributionInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetStreamingDistributionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStreamingDistribution", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetStreamingDistributionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamingDistribution indicates an expected call of GetStreamingDistribution.
func (mr *MockCloudfrontClientMockRecorder) GetStreamingDistribution(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamingDistribution", reflect.TypeOf((*MockCloudfrontClient)(nil).GetStreamingDistribution), varargs...)
}

// GetStreamingDistributionConfig mocks base method.
func (m *MockCloudfrontClient) GetStreamingDistributionConfig(arg0 context.Context, arg1 *cloudfront.GetStreamingDistributionConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetStreamingDistributionConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStreamingDistributionConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetStreamingDistributionConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamingDistributionConfig indicates an expected call of GetStreamingDistributionConfig.
func (mr *MockCloudfrontClientMockRecorder) GetStreamingDistributionConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamingDistributionConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).GetStreamingDistributionConfig), varargs...)
}

// GetVpcOrigin mocks base method.
func (m *MockCloudfrontClient) GetVpcOrigin(arg0 context.Context, arg1 *cloudfront.GetVpcOriginInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetVpcOriginOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetVpcOrigin", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetVpcOriginOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVpcOrigin indicates an expected call of GetVpcOrigin.
func (mr *MockCloudfrontClientMockRecorder) GetVpcOrigin(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVpcOrigin", reflect.TypeOf((*MockCloudfrontClient)(nil).GetVpcOrigin), varargs...)
}

// ListAnycastIpLists mocks base method.
func (m *MockCloudfrontClient) ListAnycastIpLists(arg0 context.Context, arg1 *cloudfront.ListAnycastIpListsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListAnycastIpListsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAnycastIpLists", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListAnycastIpListsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAnycastIpLists indicates an expected call of ListAnycastIpLists.
func (mr *MockCloudfrontClientMockRecorder) ListAnycastIpLists(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAnycastIpLists", reflect.TypeOf((*MockCloudfrontClient)(nil).ListAnycastIpLists), varargs...)
}

// ListCachePolicies mocks base method.
func (m *MockCloudfrontClient) ListCachePolicies(arg0 context.Context, arg1 *cloudfront.ListCachePoliciesInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListCachePoliciesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListCachePolicies", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListCachePoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCachePolicies indicates an expected call of ListCachePolicies.
func (mr *MockCloudfrontClientMockRecorder) ListCachePolicies(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCachePolicies", reflect.TypeOf((*MockCloudfrontClient)(nil).ListCachePolicies), varargs...)
}

// ListCloudFrontOriginAccessIdentities mocks base method.
func (m *MockCloudfrontClient) ListCloudFrontOriginAccessIdentities(arg0 context.Context, arg1 *cloudfront.ListCloudFrontOriginAccessIdentitiesInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListCloudFrontOriginAccessIdentitiesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListCloudFrontOriginAccessIdentities", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListCloudFrontOriginAccessIdentitiesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCloudFrontOriginAccessIdentities indicates an expected call of ListCloudFrontOriginAccessIdentities.
func (mr *MockCloudfrontClientMockRecorder) ListCloudFrontOriginAccessIdentities(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCloudFrontOriginAccessIdentities", reflect.TypeOf((*MockCloudfrontClient)(nil).ListCloudFrontOriginAccessIdentities), varargs...)
}

// ListConflictingAliases mocks base method.
func (m *MockCloudfrontClient) ListConflictingAliases(arg0 context.Context, arg1 *cloudfront.ListConflictingAliasesInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListConflictingAliasesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListConflictingAliases", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListConflictingAliasesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConflictingAliases indicates an expected call of ListConflictingAliases.
func (mr *MockCloudfrontClientMockRecorder) ListConflictingAliases(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConflictingAliases", reflect.TypeOf((*MockCloudfrontClient)(nil).ListConflictingAliases), varargs...)
}

// ListConnectionGroups mocks base method.
func (m *MockCloudfrontClient) ListConnectionGroups(arg0 context.Context, arg1 *cloudfront.ListConnectionGroupsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListConnectionGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListConnectionGroups", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListConnectionGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnectionGroups indicates an expected call of ListConnectionGroups.
func (mr *MockCloudfrontClientMockRecorder) ListConnectionGroups(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectionGroups", reflect.TypeOf((*MockCloudfrontClient)(nil).ListConnectionGroups), varargs...)
}

// ListContinuousDeploymentPolicies mocks base method.
func (m *MockCloudfrontClient) ListContinuousDeploymentPolicies(arg0 context.Context, arg1 *cloudfront.ListContinuousDeploymentPoliciesInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListContinuousDeploymentPoliciesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListContinuousDeploymentPolicies", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListContinuousDeploymentPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContinuousDeploymentPolicies indicates an expected call of ListContinuousDeploymentPolicies.
func (mr *MockCloudfrontClientMockRecorder) ListContinuousDeploymentPolicies(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContinuousDeploymentPolicies", reflect.TypeOf((*MockCloudfrontClient)(nil).ListContinuousDeploymentPolicies), varargs...)
}

// ListDistributionTenants mocks base method.
func (m *MockCloudfrontClient) ListDistributionTenants(arg0 context.Context, arg1 *cloudfront.ListDistributionTenantsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionTenantsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionTenants", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionTenantsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionTenants indicates an expected call of ListDistributionTenants.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionTenants(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionTenants", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionTenants), varargs...)
}

// ListDistributionTenantsByCustomization mocks base method.
func (m *MockCloudfrontClient) ListDistributionTenantsByCustomization(arg0 context.Context, arg1 *cloudfront.ListDistributionTenantsByCustomizationInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionTenantsByCustomizationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionTenantsByCustomization", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionTenantsByCustomizationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionTenantsByCustomization indicates an expected call of ListDistributionTenantsByCustomization.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionTenantsByCustomization(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionTenantsByCustomization", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionTenantsByCustomization), varargs...)
}

// ListDistributions mocks base method.
func (m *MockCloudfrontClient) ListDistributions(arg0 context.Context, arg1 *cloudfront.ListDistributionsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributions", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributions indicates an expected call of ListDistributions.
func (mr *MockCloudfrontClientMockRecorder) ListDistributions(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributions", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributions), varargs...)
}

// ListDistributionsByAnycastIpListId mocks base method.
func (m *MockCloudfrontClient) ListDistributionsByAnycastIpListId(arg0 context.Context, arg1 *cloudfront.ListDistributionsByAnycastIpListIdInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsByAnycastIpListIdOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionsByAnycastIpListId", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsByAnycastIpListIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionsByAnycastIpListId indicates an expected call of ListDistributionsByAnycastIpListId.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionsByAnycastIpListId(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionsByAnycastIpListId", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionsByAnycastIpListId), varargs...)
}

// ListDistributionsByCachePolicyId mocks base method.
func (m *MockCloudfrontClient) ListDistributionsByCachePolicyId(arg0 context.Context, arg1 *cloudfront.ListDistributionsByCachePolicyIdInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsByCachePolicyIdOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionsByCachePolicyId", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsByCachePolicyIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionsByCachePolicyId indicates an expected call of ListDistributionsByCachePolicyId.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionsByCachePolicyId(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionsByCachePolicyId", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionsByCachePolicyId), varargs...)
}

// ListDistributionsByConnectionMode mocks base method.
func (m *MockCloudfrontClient) ListDistributionsByConnectionMode(arg0 context.Context, arg1 *cloudfront.ListDistributionsByConnectionModeInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsByConnectionModeOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionsByConnectionMode", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsByConnectionModeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionsByConnectionMode indicates an expected call of ListDistributionsByConnectionMode.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionsByConnectionMode(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionsByConnectionMode", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionsByConnectionMode), varargs...)
}

// ListDistributionsByKeyGroup mocks base method.
func (m *MockCloudfrontClient) ListDistributionsByKeyGroup(arg0 context.Context, arg1 *cloudfront.ListDistributionsByKeyGroupInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsByKeyGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionsByKeyGroup", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsByKeyGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionsByKeyGroup indicates an expected call of ListDistributionsByKeyGroup.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionsByKeyGroup(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionsByKeyGroup", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionsByKeyGroup), varargs...)
}

// ListDistributionsByOriginRequestPolicyId mocks base method.
func (m *MockCloudfrontClient) ListDistributionsByOriginRequestPolicyId(arg0 context.Context, arg1 *cloudfront.ListDistributionsByOriginRequestPolicyIdInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsByOriginRequestPolicyIdOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionsByOriginRequestPolicyId", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsByOriginRequestPolicyIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionsByOriginRequestPolicyId indicates an expected call of ListDistributionsByOriginRequestPolicyId.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionsByOriginRequestPolicyId(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionsByOriginRequestPolicyId", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionsByOriginRequestPolicyId), varargs...)
}

// ListDistributionsByRealtimeLogConfig mocks base method.
func (m *MockCloudfrontClient) ListDistributionsByRealtimeLogConfig(arg0 context.Context, arg1 *cloudfront.ListDistributionsByRealtimeLogConfigInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsByRealtimeLogConfigOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionsByRealtimeLogConfig", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsByRealtimeLogConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionsByRealtimeLogConfig indicates an expected call of ListDistributionsByRealtimeLogConfig.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionsByRealtimeLogConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionsByRealtimeLogConfig", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionsByRealtimeLogConfig), varargs...)
}

// ListDistributionsByResponseHeadersPolicyId mocks base method.
func (m *MockCloudfrontClient) ListDistributionsByResponseHeadersPolicyId(arg0 context.Context, arg1 *cloudfront.ListDistributionsByResponseHeadersPolicyIdInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsByResponseHeadersPolicyIdOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionsByResponseHeadersPolicyId", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsByResponseHeadersPolicyIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionsByResponseHeadersPolicyId indicates an expected call of ListDistributionsByResponseHeadersPolicyId.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionsByResponseHeadersPolicyId(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionsByResponseHeadersPolicyId", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionsByResponseHeadersPolicyId), varargs...)
}

// ListDistributionsByVpcOriginId mocks base method.
func (m *MockCloudfrontClient) ListDistributionsByVpcOriginId(arg0 context.Context, arg1 *cloudfront.ListDistributionsByVpcOriginIdInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsByVpcOriginIdOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionsByVpcOriginId", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsByVpcOriginIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionsByVpcOriginId indicates an expected call of ListDistributionsByVpcOriginId.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionsByVpcOriginId(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionsByVpcOriginId", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionsByVpcOriginId), varargs...)
}

// ListDistributionsByWebACLId mocks base method.
func (m *MockCloudfrontClient) ListDistributionsByWebACLId(arg0 context.Context, arg1 *cloudfront.ListDistributionsByWebACLIdInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsByWebACLIdOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDistributionsByWebACLId", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDistributionsByWebACLIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistributionsByWebACLId indicates an expected call of ListDistributionsByWebACLId.
func (mr *MockCloudfrontClientMockRecorder) ListDistributionsByWebACLId(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistributionsByWebACLId", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDistributionsByWebACLId), varargs...)
}

// ListDomainConflicts mocks base method.
func (m *MockCloudfrontClient) ListDomainConflicts(arg0 context.Context, arg1 *cloudfront.ListDomainConflictsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListDomainConflictsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDomainConflicts", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListDomainConflictsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDomainConflicts indicates an expected call of ListDomainConflicts.
func (mr *MockCloudfrontClientMockRecorder) ListDomainConflicts(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDomainConflicts", reflect.TypeOf((*MockCloudfrontClient)(nil).ListDomainConflicts), varargs...)
}

// ListFieldLevelEncryptionConfigs mocks base method.
func (m *MockCloudfrontClient) ListFieldLevelEncryptionConfigs(arg0 context.Context, arg1 *cloudfront.ListFieldLevelEncryptionConfigsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListFieldLevelEncryptionConfigsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFieldLevelEncryptionConfigs", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListFieldLevelEncryptionConfigsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFieldLevelEncryptionConfigs indicates an expected call of ListFieldLevelEncryptionConfigs.
func (mr *MockCloudfrontClientMockRecorder) ListFieldLevelEncryptionConfigs(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFieldLevelEncryptionConfigs", reflect.TypeOf((*MockCloudfrontClient)(nil).ListFieldLevelEncryptionConfigs), varargs...)
}

// ListFieldLevelEncryptionProfiles mocks base method.
func (m *MockCloudfrontClient) ListFieldLevelEncryptionProfiles(arg0 context.Context, arg1 *cloudfront.ListFieldLevelEncryptionProfilesInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListFieldLevelEncryptionProfilesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFieldLevelEncryptionProfiles", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListFieldLevelEncryptionProfilesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFieldLevelEncryptionProfiles indicates an expected call of ListFieldLevelEncryptionProfiles.
func (mr *MockCloudfrontClientMockRecorder) ListFieldLevelEncryptionProfiles(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFieldLevelEncryptionProfiles", reflect.TypeOf((*MockCloudfrontClient)(nil).ListFieldLevelEncryptionProfiles), varargs...)
}

// ListFunctions mocks base method.
func (m *MockCloudfrontClient) ListFunctions(arg0 context.Context, arg1 *cloudfront.ListFunctionsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListFunctionsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFunctions", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListFunctionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFunctions indicates an expected call of ListFunctions.
func (mr *MockCloudfrontClientMockRecorder) ListFunctions(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFunctions", reflect.TypeOf((*MockCloudfrontClient)(nil).ListFunctions), varargs...)
}

// ListInvalidations mocks base method.
func (m *MockCloudfrontClient) ListInvalidations(arg0 context.Context, arg1 *cloudfront.ListInvalidationsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListInvalidationsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInvalidations", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListInvalidationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvalidations indicates an expected call of ListInvalidations.
func (mr *MockCloudfrontClientMockRecorder) ListInvalidations(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvalidations", reflect.TypeOf((*MockCloudfrontClient)(nil).ListInvalidations), varargs...)
}

// ListInvalidationsForDistributionTenant mocks base method.
func (m *MockCloudfrontClient) ListInvalidationsForDistributionTenant(arg0 context.Context, arg1 *cloudfront.ListInvalidationsForDistributionTenantInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListInvalidationsForDistributionTenantOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInvalidationsForDistributionTenant", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListInvalidationsForDistributionTenantOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvalidationsForDistributionTenant indicates an expected call of ListInvalidationsForDistributionTenant.
func (mr *MockCloudfrontClientMockRecorder) ListInvalidationsForDistributionTenant(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvalidationsForDistributionTenant", reflect.TypeOf((*MockCloudfrontClient)(nil).ListInvalidationsForDistributionTenant), varargs...)
}

// ListKeyGroups mocks base method.
func (m *MockCloudfrontClient) ListKeyGroups(arg0 context.Context, arg1 *cloudfront.ListKeyGroupsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListKeyGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListKeyGroups", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListKeyGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeyGroups indicates an expected call of ListKeyGroups.
func (mr *MockCloudfrontClientMockRecorder) ListKeyGroups(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeyGroups", reflect.TypeOf((*MockCloudfrontClient)(nil).ListKeyGroups), varargs...)
}

// ListKeyValueStores mocks base method.
func (m *MockCloudfrontClient) ListKeyValueStores(arg0 context.Context, arg1 *cloudfront.ListKeyValueStoresInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListKeyValueStoresOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListKeyValueStores", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListKeyValueStoresOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeyValueStores indicates an expected call of ListKeyValueStores.
func (mr *MockCloudfrontClientMockRecorder) ListKeyValueStores(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeyValueStores", reflect.TypeOf((*MockCloudfrontClient)(nil).ListKeyValueStores), varargs...)
}

// ListOriginAccessControls mocks base method.
func (m *MockCloudfrontClient) ListOriginAccessControls(arg0 context.Context, arg1 *cloudfront.ListOriginAccessControlsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListOriginAccessControlsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOriginAccessControls", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListOriginAccessControlsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOriginAccessControls indicates an expected call of ListOriginAccessControls.
func (mr *MockCloudfrontClientMockRecorder) ListOriginAccessControls(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOriginAccessControls", reflect.TypeOf((*MockCloudfrontClient)(nil).ListOriginAccessControls), varargs...)
}

// ListOriginRequestPolicies mocks base method.
func (m *MockCloudfrontClient) ListOriginRequestPolicies(arg0 context.Context, arg1 *cloudfront.ListOriginRequestPoliciesInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListOriginRequestPoliciesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOriginRequestPolicies", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListOriginRequestPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOriginRequestPolicies indicates an expected call of ListOriginRequestPolicies.
func (mr *MockCloudfrontClientMockRecorder) ListOriginRequestPolicies(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOriginRequestPolicies", reflect.TypeOf((*MockCloudfrontClient)(nil).ListOriginRequestPolicies), varargs...)
}

// ListPublicKeys mocks base method.
func (m *MockCloudfrontClient) ListPublicKeys(arg0 context.Context, arg1 *cloudfront.ListPublicKeysInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListPublicKeysOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPublicKeys", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListPublicKeysOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicKeys indicates an expected call of ListPublicKeys.
func (mr *MockCloudfrontClientMockRecorder) ListPublicKeys(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicKeys", reflect.TypeOf((*MockCloudfrontClient)(nil).ListPublicKeys), varargs...)
}

// ListRealtimeLogConfigs mocks base method.
func (m *MockCloudfrontClient) ListRealtimeLogConfigs(arg0 context.Context, arg1 *cloudfront.ListRealtimeLogConfigsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListRealtimeLogConfigsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListRealtimeLogConfigs", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListRealtimeLogConfigsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRealtimeLogConfigs indicates an expected call of ListRealtimeLogConfigs.
func (mr *MockCloudfrontClientMockRecorder) ListRealtimeLogConfigs(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRealtimeLogConfigs", reflect.TypeOf((*MockCloudfrontClient)(nil).ListRealtimeLogConfigs), varargs...)
}

// ListResponseHeadersPolicies mocks base method.
func (m *MockCloudfrontClient) ListResponseHeadersPolicies(arg0 context.Context, arg1 *cloudfront.ListResponseHeadersPoliciesInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListResponseHeadersPoliciesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListResponseHeadersPolicies", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListResponseHeadersPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResponseHeadersPolicies indicates an expected call of ListResponseHeadersPolicies.
func (mr *MockCloudfrontClientMockRecorder) ListResponseHeadersPolicies(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResponseHeadersPolicies", reflect.TypeOf((*MockCloudfrontClient)(nil).ListResponseHeadersPolicies), varargs...)
}

// ListStreamingDistributions mocks base method.
func (m *MockCloudfrontClient) ListStreamingDistributions(arg0 context.Context, arg1 *cloudfront.ListStreamingDistributionsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListStreamingDistributionsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListStreamingDistributions", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListStreamingDistributionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStreamingDistributions indicates an expected call of ListStreamingDistributions.
func (mr *MockCloudfrontClientMockRecorder) ListStreamingDistributions(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStreamingDistributions", reflect.TypeOf((*MockCloudfrontClient)(nil).ListStreamingDistributions), varargs...)
}

// ListTagsForResource mocks base method.
func (m *MockCloudfrontClient) ListTagsForResource(arg0 context.Context, arg1 *cloudfront.ListTagsForResourceInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListTagsForResourceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTagsForResource", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListTagsForResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForResource indicates an expected call of ListTagsForResource.
func (mr *MockCloudfrontClientMockRecorder) ListTagsForResource(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForResource", reflect.TypeOf((*MockCloudfrontClient)(nil).ListTagsForResource), varargs...)
}

// ListVpcOrigins mocks base method.
func (m *MockCloudfrontClient) ListVpcOrigins(arg0 context.Context, arg1 *cloudfront.ListVpcOriginsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListVpcOriginsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListVpcOrigins", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListVpcOriginsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVpcOrigins indicates an expected call of ListVpcOrigins.
func (mr *MockCloudfrontClientMockRecorder) ListVpcOrigins(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVpcOrigins", reflect.TypeOf((*MockCloudfrontClient)(nil).ListVpcOrigins), varargs...)
}
