version: "2"
run:
  build-tags:
    - all
  tests: true
linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - gocritic
    - importas
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
  settings:
    dupl:
      threshold: 500
    errcheck:
      check-blank: false
    gocritic:
      disabled-checks:
        - commentFormatting
    revive:
      enable-all-rules: true
      rules:
        - name: cyclomatic
          disabled: true
        - name: argument-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: file-header
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: banned-characters
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: add-constant
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: var-naming
          disabled: true
        - name: deep-exit
          disabled: true
        - name: exported
          arguments:
            - disableStutteringCheck
          disabled: false
        - name: unused-parameter
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: confusing-results
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: nested-structs
          disabled: true
        - name: unchecked-type-assertion
          disabled: true
        - name: import-alias-naming
          disabled: true
        - name: use-errors-new
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocritic
          - revive
        path: _test\.go
      - linters:
          - dupl
        path: resources(\\|\/).*\.go
      - linters:
          - dupl
        path: services\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - resources/forks
      - codegen
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
