# Test unit
.PHONY: test
test:
	go test -race -timeout 3m ./...

# Install tools
.PHONY: install-tools
install-tools:
	@echo Installing tools from tools/tool.go
	@cat tools/tool.go | grep _ | awk -F'"' '{print $$2}' | xargs -tI % go install %

# Install pre-commit hooks. This requires pre-commit to be installed (https://pre-commit.com/)
#.PHONY: install-hooks
#install-hooks:
#	pre-commit install

.PHONY: lint
lint:
	golangci-lint run --config .golangci.yml

.PHONY: gen-mocks
gen-mocks:
	go install github.com/golang/mock/mockgen@v1.6.0
	grep -rl '// Code generated by codegen; DO NOT EDIT.' ./client/services/* | xargs rm
	go run codegen/main.go
	grep -rl '// Code generated by MockGen. DO NOT EDIT.' ./client/mocks/* | xargs rm
	go generate ./client/...
	go run client/mockassert/main.go

.PHONY: gen-docs
gen-docs:
	rm -rf ./docs/tables/*
	go run main.go doc ./docs/tables
	sed 's_(\(.*\))_(https://github.com/OpsHelmInc/cloudquery/blob/main/docs/tables/\1)_' docs/tables/README.md > ./website/pages/docs/tables.md
	go run main.go doc --format json docs
	rm docs/__tables.json

.PHONY: gen-spec-schema
gen-spec-schema:
	# required for loading comments from AWS SDK
	go mod vendor
	go run client/spec/gen/main.go

# All gen targets
.PHONY: gen
gen: gen-spec-schema gen-mocks gen-docs
