// Code generated by codegen; DO NOT EDIT.

package glue

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func Connections() *schema.Table {
	return &schema.Table{
		Name:      "aws_glue_connections",
		Resolver:  fetchGlueConnections,
		Multiplex: client.ServiceAccountRegionMultiplexer("glue"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: resolveGlueConnectionArn,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "athena_properties",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("AthenaProperties"),
			},
			{
				Name:     "authentication_configuration",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("AuthenticationConfiguration"),
			},
			{
				Name:     "compatible_compute_environments",
				Type:     schema.TypeStringArray,
				Resolver: schema.PathResolver("CompatibleComputeEnvironments"),
			},
			{
				Name:     "connection_properties",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("ConnectionProperties"),
			},
			{
				Name:     "connection_schema_version",
				Type:     schema.TypeInt,
				Resolver: schema.PathResolver("ConnectionSchemaVersion"),
			},
			{
				Name:     "connection_type",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ConnectionType"),
			},
			{
				Name:     "creation_time",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("CreationTime"),
			},
			{
				Name:     "description",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Description"),
			},
			{
				Name:     "last_connection_validation_time",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("LastConnectionValidationTime"),
			},
			{
				Name:     "last_updated_by",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LastUpdatedBy"),
			},
			{
				Name:     "last_updated_time",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("LastUpdatedTime"),
			},
			{
				Name:     "match_criteria",
				Type:     schema.TypeStringArray,
				Resolver: schema.PathResolver("MatchCriteria"),
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "physical_connection_requirements",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("PhysicalConnectionRequirements"),
			},
			{
				Name:     "python_properties",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("PythonProperties"),
			},
			{
				Name:     "spark_properties",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("SparkProperties"),
			},
			{
				Name:     "status",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Status"),
			},
			{
				Name:     "status_reason",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("StatusReason"),
			},
		},
	}
}
