// Code generated by codegen; DO NOT EDIT.

package glue

import (
	"github.com/cloudquery/plugin-sdk/schema"

	"github.com/OpsHelmInc/cloudquery/client"
)

func Databases() *schema.Table {
	return &schema.Table{
		Name:                "aws_glue_databases",
		Resolver:            fetchGlueDatabases,
		PreResourceResolver: getGlueDatabase,
		Multiplex:           client.ServiceAccountRegionMultiplexer("glue"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: resolveGlueDatabaseArn,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "catalog_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("CatalogId"),
			},
			{
				Name:     "create_table_default_permissions",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("CreateTableDefaultPermissions"),
			},
			{
				Name:     "create_time",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("CreateTime"),
			},
			{
				Name:     "description",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Description"),
			},
			{
				Name:     "federated_database",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("FederatedDatabase"),
			},
			{
				Name:     "location_uri",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LocationUri"),
			},
			{
				Name:     "parameters",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Parameters"),
			},
			{
				Name:     "target_database",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("TargetDatabase"),
			},
			{
				Name:     "tags",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Tags"),
			},
		},

		Relations: []*schema.Table{
			DatabaseTables(),
		},
	}
}
