// Code generated by codegen; DO NOT EDIT.

package iam

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func Groups() *schema.Table {
	return &schema.Table{
		Name:                "aws_iam_groups",
		Description:         `https://docs.aws.amazon.com/IAM/latest/APIReference/API_Group.html`,
		Resolver:            fetchIamGroups,
		PreResourceResolver: getGroup,
		Multiplex:           client.AccountMultiplex,
		Columns: []schema.Column{
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Arn"),
			},
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("GroupId"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "oh_resource_type",
				Type:     schema.TypeString,
				Resolver: client.StaticValueResolver("AWS::IAM::Group"),
			},
			{
				Name:     "group",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Group"),
			},
			{
				Name:     "users",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Users"),
			},
			{
				Name:     "policies",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Policies"),
			},
		},

		Relations: []*schema.Table{
			GroupPolicies(),
		},
	}
}
