// Code generated by codegen; DO NOT EDIT.

package iam

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func PasswordPolicies() *schema.Table {
	return &schema.Table{
		Name:      "aws_iam_password_policies",
		Resolver:  fetchIamPasswordPolicies,
		Multiplex: client.AccountMultiplex,
		Columns: []schema.Column{
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: resolvePasswordPolicyArn,
			},
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "oh_resource_type",
				Type:     schema.TypeString,
				Resolver: client.StaticValueResolver("AWS::IAM::AccountPasswordPolicy"),
			},
			{
				Name:     "password_policy",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("PasswordPolicy"),
			},
			{
				Name:     "policy_exists",
				Type:     schema.TypeBool,
				Resolver: schema.PathResolver("PolicyExists"),
			},
		},
	}
}
