// Code generated by codegen; DO NOT EDIT.

package iam

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func UserAccessKeys() *schema.Table {
	return &schema.Table{
		Name:      "aws_iam_user_access_keys",
		Resolver:  fetchIamUserAccessKeys,
		Multiplex: client.AccountMultiplex,
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: resolveAccessKeyArn,
			},
			{
				Name:     "user_arn",
				Type:     schema.TypeString,
				Resolver: schema.ParentColumnResolver("arn"),
			},
			{
				Name:     "user_id",
				Type:     schema.TypeString,
				Resolver: schema.ParentColumnResolver("id"),
			},
			{
				Name:     "oh_resource_type",
				Type:     schema.TypeString,
				Resolver: client.StaticValueResolver("AWS::IAM::AccessKey"),
			},
			{
				Name:     "access_key_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("AccessKeyId"),
			},
			{
				Name:     "create_date",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("CreateDate"),
			},
			{
				Name:     "status",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Status"),
			},
			{
				Name:     "user_name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("UserName"),
			},
			{
				Name:     "last_used_date",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("LastUsedDate"),
			},
			{
				Name:     "last_used_region",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LastUsedRegion"),
			},
			{
				Name:     "last_used_service_name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LastUsedServiceName"),
			},
		},
	}
}
