// Code generated by codegen; DO NOT EDIT.

package elbv2

import (
	"github.com/cloudquery/plugin-sdk/schema"

	"github.com/OpsHelmInc/cloudquery/client"
)

func Listeners() *schema.Table {
	return &schema.Table{
		Name:                "aws_elbv2_listeners",
		Description:         `https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_Listener.html`,
		Resolver:            fetchElbv2Listeners,
		PreResourceResolver: getLoadBalancerListener,
		Multiplex:           client.ServiceAccountRegionMultiplexer("elasticloadbalancing"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ListenerArn"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "oh_resource_type",
				Type:     schema.TypeString,
				Resolver: client.StaticValueResolver("AWS::ElasticLoadBalancingV2::Listener"),
			},
			{
				Name:     "listener",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Listener"),
			},
			{
				Name:     "tags",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Tags"),
			},
		},

		Relations: []*schema.Table{
			ListenerCertificates(),
		},
	}
}
