// Code generated by codegen; DO NOT EDIT.

package elbv2

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func TargetGroups() *schema.Table {
	return &schema.Table{
		Name:                "aws_elbv2_target_groups",
		Description:         `https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetGroup.html`,
		Resolver:            fetchElbv2TargetGroups,
		PreResourceResolver: getTargetGroup,
		Multiplex:           client.ServiceAccountRegionMultiplexer("elasticloadbalancing"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("TargetGroupArn"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "oh_resource_type",
				Type:     schema.TypeString,
				Resolver: client.StaticValueResolver("AWS::ElasticLoadBalancingV2::TargetGroup"),
			},
			{
				Name:     "target_group",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("TargetGroup"),
			},
			{
				Name:     "tags",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Tags"),
			},
			{
				Name:     "unknown_attributes",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("UnknownAttributes"),
			},
		},

		Relations: []*schema.Table{
			TargetGroupTargetHealthDescriptions(),
		},
	}
}
