// Code generated by codegen; DO NOT EDIT.

package sagemaker

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func Models() *schema.Table {
	return &schema.Table{
		Name:                "aws_sagemaker_models",
		Resolver:            fetchSagemakerModels,
		PreResourceResolver: getModel,
		Multiplex:           client.ServiceAccountRegionMultiplexer("api.sagemaker"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ModelArn"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:        "tags",
				Type:        schema.TypeJSON,
				Resolver:    resolveSagemakerModelTags,
				Description: `The tags associated with the model.`,
			},
			{
				Name:     "oh_resource_type",
				Type:     schema.TypeString,
				Resolver: client.StaticValueResolver("AWS::SageMaker::Model"),
			},
			{
				Name:     "creation_time",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("CreationTime"),
			},
			{
				Name:     "model_name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ModelName"),
			},
			{
				Name:     "containers",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Containers"),
			},
			{
				Name:     "deployment_recommendation",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("DeploymentRecommendation"),
			},
			{
				Name:     "enable_network_isolation",
				Type:     schema.TypeBool,
				Resolver: schema.PathResolver("EnableNetworkIsolation"),
			},
			{
				Name:     "execution_role_arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ExecutionRoleArn"),
			},
			{
				Name:     "inference_execution_config",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("InferenceExecutionConfig"),
			},
			{
				Name:     "primary_container",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("PrimaryContainer"),
			},
			{
				Name:     "vpc_config",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("VpcConfig"),
			},
			{
				Name:     "result_metadata",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("ResultMetadata"),
			},
		},
	}
}
