// Code generated by codegen; DO NOT EDIT.

package lambda

import (
	"github.com/cloudquery/plugin-sdk/schema"

	"github.com/OpsHelmInc/cloudquery/client"
)

func FunctionAliases() *schema.Table {
	return &schema.Table{
		Name:                "aws_lambda_function_aliases",
		Resolver:            fetchLambdaFunctionAliases,
		PreResourceResolver: getFunctionAliasURLConfig,
		Multiplex:           client.ServiceAccountRegionMultiplexer("lambda"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "function_arn",
				Type:     schema.TypeString,
				Resolver: schema.ParentColumnResolver("arn"),
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("AliasArn"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "alias_configuration",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("AliasConfiguration"),
			},
			{
				Name:     "url_config",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("UrlConfig"),
			},
		},
	}
}
