// Code generated by codegen; DO NOT EDIT.

package ecrpublic

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func Repositories() *schema.Table {
	return &schema.Table{
		Name:                "aws_ecrpublic_repositories",
		Description:         `https://docs.aws.amazon.com/AmazonECRPublic/latest/APIReference/API_Repository.html`,
		Resolver:            fetchEcrpublicRepositories,
		PreResourceResolver: getRepository,
		Multiplex:           client.ServiceAccountRegionMultiplexer("api.ecr-public"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("RepositoryArn"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "oh_resource_type",
				Type:     schema.TypeString,
				Resolver: client.StaticValueResolver("AWS::ECR::PublicRepository"),
			},
			{
				Name:     "repository",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Repository"),
			},
			{
				Name:     "tags",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Tags"),
			},
		},

		Relations: []*schema.Table{
			RepositoryImages(),
		},
	}
}
