// Code generated by codegen; DO NOT EDIT.

package config

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func ConfigurationRecorders() *schema.Table {
	return &schema.Table{
		Name:      "aws_config_configuration_recorders",
		Resolver:  fetchConfigConfigurationRecorders,
		Multiplex: client.ServiceAccountRegionMultiplexer("config"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Arn"),
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "recording_group",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("RecordingGroup"),
			},
			{
				Name:     "recording_mode",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("RecordingMode"),
			},
			{
				Name:     "recording_scope",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("RecordingScope"),
			},
			{
				Name:     "role_arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("RoleARN"),
			},
			{
				Name:     "service_principal",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ServicePrincipal"),
			},
			{
				Name:     "status_last_error_code",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("StatusLastErrorCode"),
			},
			{
				Name:     "status_last_error_message",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("StatusLastErrorMessage"),
			},
			{
				Name:     "status_last_start_time",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("StatusLastStartTime"),
			},
			{
				Name:     "status_last_status",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("StatusLastStatus"),
			},
			{
				Name:     "status_last_status_change_time",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("StatusLastStatusChangeTime"),
			},
			{
				Name:     "status_last_stop_time",
				Type:     schema.TypeTimestamp,
				Resolver: schema.PathResolver("StatusLastStopTime"),
			},
			{
				Name:     "status_recording",
				Type:     schema.TypeBool,
				Resolver: schema.PathResolver("StatusRecording"),
			},
		},
	}
}
