// Code generated by codegen; DO NOT EDIT.

package ec2

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func LaunchTemplates() *schema.Table {
	return &schema.Table{
		Name:                "aws_ec2_launch_templates",
		Description:         `https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ResponseLaunchTemplateData.html`,
		Resolver:            fetchEc2LaunchTemplates,
		PreResourceResolver: getLaunchTemplate,
		Multiplex:           client.ServiceAccountRegionMultiplexer("ec2"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "launch_template_id",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("LaunchTemplateId"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "launch_template_data",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("LaunchTemplateData"),
			},
		},
	}
}
