// Code generated by codegen; DO NOT EDIT.

package backup

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func Vaults() *schema.Table {
	return &schema.Table{
		Name:                "aws_backup_vaults",
		Description:         `https://docs.aws.amazon.com/aws-backup/latest/devguide/API_BackupVaultListMember.html`,
		Resolver:            fetchBackupVaults,
		PreResourceResolver: getBackupVault,
		Multiplex:           client.ServiceAccountRegionMultiplexer("backup"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("BackupVaultArn"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:          "access_policy",
				Type:          schema.TypeJSON,
				Resolver:      resolveVaultAccessPolicy,
				IgnoreInTests: true,
			},
			{
				Name:          "notifications",
				Type:          schema.TypeJSON,
				Resolver:      resolveVaultNotifications,
				IgnoreInTests: true,
			},
			{
				Name:     "backup_vault_list_member",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("BackupVaultListMember"),
			},
			{
				Name:     "tags",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Tags"),
			},
		},

		Relations: []*schema.Table{
			VaultRecoveryPoints(),
		},
	}
}
