// Code generated by codegen; DO NOT EDIT.

package budgets

import (
	"github.com/cloudquery/plugin-sdk/schema"

	"github.com/OpsHelmInc/cloudquery/client"
)

func Budgets() *schema.Table {
	return &schema.Table{
		Name:                "aws_budgets_budgets",
		Description:         `https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsbudgetservice.html`,
		Resolver:            fetchBudgetsBudgets,
		PreResourceResolver: getBudget,
		Multiplex:           client.ServiceAccountRegionMultiplexer("budgets"),
		Columns: []schema.Column{
			{
				Name:     "budget",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Budget"),
			},
		},
	}
}
