// Code generated by codegen; DO NOT EDIT.

package wafv2

import (
	"github.com/OpsHelmInc/cloudquery/client"
	"github.com/cloudquery/plugin-sdk/schema"
)

func RuleGroups() *schema.Table {
	return &schema.Table{
		Name:                "aws_wafv2_rule_groups",
		Description:         `https://docs.aws.amazon.com/waf/latest/APIReference/API_RuleGroup.html`,
		Resolver:            fetchWafv2RuleGroups,
		PreResourceResolver: getRuleGroup,
		Multiplex:           client.ServiceAccountRegionScopeMultiplexer("waf-regional"),
		Columns: []schema.Column{
			{
				Name:     "account_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSAccount,
			},
			{
				Name:     "region",
				Type:     schema.TypeString,
				Resolver: client.ResolveAWSRegion,
			},
			{
				Name:     "arn",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("ARN"),
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name:     "policy",
				Type:     schema.TypeJSON,
				Resolver: resolveWafv2ruleGroupPolicy,
			},
			{
				Name:     "rule_group",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("RuleGroup"),
			},
			{
				Name:     "tags",
				Type:     schema.TypeJSON,
				Resolver: client.ResolveTags,
			},
		},
	}
}
