on: pull_request
name: Check Commit

jobs:
  check_commit:
    name: Check Commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.20.0'
    - name: Get Go cache paths
      id: cache-path
      run: |
        echo "build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
        echo "module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
      shell: bash
    - name: Setup Cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.cache-path.outputs.build }}
          ${{ steps.cache-path.outputs.module }}
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - name: Install Tools
      run: make install-tools
    - name: Gen
      run: make gen
    - name: Fail if generation updated files
      run: test "$(git status -s | wc -l)" -eq 0 || (git status -s; exit 1)
    - name: Check
      run: make test
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.2
        args: --timeout=5m